"""add color

Revision ID: 45433f2a6b35
Revises: 5a393817fd8e
Create Date: 2026-01-25 18:32:19.569068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45433f2a6b35'
down_revision: Union[str, Sequence[str], None] = '5a393817fd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'color')
    # ### end Alembic commands ###
