"""add gender and weight

Revision ID: 5a393817fd8e
Revises: e87fbde6bed6
Create Date: 2026-01-25 18:12:30.609562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a393817fd8e'
down_revision: Union[str, Sequence[str], None] = 'e87fbde6bed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'weight')
    op.drop_column('pets', 'gender')
    # ### end Alembic commands ###
