"""add age and description

Revision ID: e87fbde6bed6
Revises: 8796e2396f9b
Create Date: 2026-01-25 17:41:11.425151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87fbde6bed6'
down_revision: Union[str, Sequence[str], None] = '8796e2396f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'description')
    op.drop_column('pets', 'age')
    # ### end Alembic commands ###
